2023-04-27 11:23:28 INFO Logging initialized. Log file: ./logs/fastapi.log,startup fastapi
2023-04-27 11:23:49 INFO Logging initialized. Log file: ./logs/fastapi.log,startup fastapi
2023-04-27 11:23:59 INFO Logging initialized. Log file: ./logs/fastapi.log,startup fastapi
2023-04-27 15:17:55 INFO Logging initialized. Log file: ./logs/fastapi.log,startup fastapi
2023-04-27 15:49:30 INFO Logging initialized. Log file: ./logs/fastapi.log,startup fastapi
2023-04-27 15:50:13 INFO Logging initialized. Log file: ./logs/fastapi.log,startup fastapi
2023-05-07 23:21:22 INFO Logging initialized. Log file: ./logs/fastapi.log,startup fastapi
2023-05-08 22:04:55 INFO Logging initialized. Log file: ./logs/fastapi.log,startup fastapi
2023-05-08 22:05:32 INFO Logging initialized. Log file: ./logs/fastapi.log,startup fastapi
2023-05-08 22:05:39 INFO Logging initialized. Log file: ./logs/fastapi.log,startup fastapi
2023-05-08 22:05:53 INFO Logging initialized. Log file: ./logs/fastapi.log,startup fastapi
2023-05-08 22:06:11 INFO Logging initialized. Log file: ./logs/fastapi.log,startup fastapi
2023-05-08 22:10:30 INFO Logging initialized. Log file: ./logs/fastapi.log,startup fastapi
2023-05-08 23:45:20 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,(pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'ops-kube_manage-mysql' ([Errno 8] nodename nor servname provided, or not known)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-05-08 23:45:22 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,(pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'ops-kube_manage-mysql' ([Errno 8] nodename nor servname provided, or not known)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-05-08 23:45:22 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,(pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'ops-kube_manage-mysql' ([Errno 8] nodename nor servname provided, or not known)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-05-08 23:45:22 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,(pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'ops-kube_manage-mysql' ([Errno 8] nodename nor servname provided, or not known)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-05-08 23:45:22 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,(pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'ops-kube_manage-mysql' ([Errno 8] nodename nor servname provided, or not known)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-05-08 23:45:23 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,(pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'ops-kube_manage-mysql' ([Errno 8] nodename nor servname provided, or not known)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-05-08 23:45:23 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,(pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'ops-kube_manage-mysql' ([Errno 8] nodename nor servname provided, or not known)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-05-08 23:45:23 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,(pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'ops-kube_manage-mysql' ([Errno 8] nodename nor servname provided, or not known)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-05-08 23:45:23 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,(pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'ops-kube_manage-mysql' ([Errno 8] nodename nor servname provided, or not known)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-05-08 23:45:24 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,(pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'ops-kube_manage-mysql' ([Errno 8] nodename nor servname provided, or not known)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-05-08 23:45:24 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,(pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'ops-kube_manage-mysql' ([Errno 8] nodename nor servname provided, or not known)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-05-08 23:45:24 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,(pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'ops-kube_manage-mysql' ([Errno 8] nodename nor servname provided, or not known)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-05-08 23:45:24 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,(pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'ops-kube_manage-mysql' ([Errno 8] nodename nor servname provided, or not known)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-05-08 23:45:24 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,(pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'ops-kube_manage-mysql' ([Errno 8] nodename nor servname provided, or not known)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-05-08 23:45:24 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,(pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'ops-kube_manage-mysql' ([Errno 8] nodename nor servname provided, or not known)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-05-08 23:45:26 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,(pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'ops-kube_manage-mysql' ([Errno 8] nodename nor servname provided, or not known)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-05-08 23:45:26 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,(pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'ops-kube_manage-mysql' ([Errno 8] nodename nor servname provided, or not known)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-05-08 23:45:26 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,(pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'ops-kube_manage-mysql' ([Errno 8] nodename nor servname provided, or not known)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-05-08 23:45:26 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,(pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'ops-kube_manage-mysql' ([Errno 8] nodename nor servname provided, or not known)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-05-08 23:45:28 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,(pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'ops-kube_manage-mysql' ([Errno 8] nodename nor servname provided, or not known)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-05-08 23:45:28 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,(pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'ops-kube_manage-mysql' ([Errno 8] nodename nor servname provided, or not known)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-05-08 23:45:28 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,(pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'ops-kube_manage-mysql' ([Errno 8] nodename nor servname provided, or not known)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-05-08 23:45:28 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,(pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'ops-kube_manage-mysql' ([Errno 8] nodename nor servname provided, or not known)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-05-10 15:31:21 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,(pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'ops-kube_manage-mysql' ([Errno 8] nodename nor servname provided, or not known)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-05-10 15:32:31 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,(pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '127.0.0.1' ([Errno 61] Connection refused)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-05-10 22:56:31 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'PodManager' object has no attribute 'api'
2023-05-10 22:56:55 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'PodManager' object has no attribute 'api'
2023-05-10 22:58:34 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'PodManager' object has no attribute 'api'
2023-05-10 23:00:42 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'AppsV1Api' object has no attribute 'list_namespaced_pod'
2023-05-10 23:00:54 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'AppsV1Api' object has no attribute 'list_namespaced_pod'
2023-05-10 23:09:55 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'V1PodStatus' object has no attribute 'ready'
2023-05-10 23:09:57 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'V1PodStatus' object has no attribute 'ready'
2023-05-10 23:11:55 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'V1PodStatus' object has no attribute 'ready'
2023-05-10 23:12:52 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: name 'pod_ready' is not defined
2023-05-10 23:41:35 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'V1PodSpec' object has no attribute 'name'
2023-05-10 23:43:12 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'list' object has no attribute 'ports'
2023-05-10 23:43:27 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'list' object has no attribute 'ports'
2023-05-10 23:53:40 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: sequence item 0: expected str instance, int found
2023-05-11 00:17:49 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: name 'pod_error_message' is not defined
2023-05-11 00:18:42 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: unhashable type: 'list'
2023-05-11 00:27:44 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'V1PodStatus' object has no attribute 'ready_replicas'
2023-05-11 00:29:54 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'V1PodStatus' object has no attribute 'replicas'
2023-05-11 00:32:13 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'V1PodSpec' object has no attribute 'replicas'
2023-05-11 00:32:15 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'V1PodSpec' object has no attribute 'replicas'
2023-05-11 00:40:00 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'V1PodSpec' object has no attribute 'replicas'
2023-05-11 00:40:50 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'NoneType' object has no attribute 'replace'
2023-05-11 00:43:44 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'V1PodSpec' object has no attribute 'replicas'
2023-05-11 00:43:45 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'V1PodSpec' object has no attribute 'replicas'
2023-05-11 00:45:16 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'NoneType' object has no attribute 'replace'
2023-05-11 00:45:55 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'NoneType' object has no attribute 'replace'
2023-05-11 00:46:26 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'NoneType' object has no attribute 'replace'
2023-05-11 00:47:11 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'NoneType' object has no attribute 'replace'
2023-05-11 00:47:12 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'NoneType' object has no attribute 'replace'
2023-05-11 00:47:13 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'NoneType' object has no attribute 'replace'
2023-05-11 00:47:14 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'NoneType' object has no attribute 'replace'
2023-05-11 00:47:15 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'NoneType' object has no attribute 'replace'
2023-05-11 00:47:17 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'NoneType' object has no attribute 'replace'
2023-05-11 00:47:20 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'NoneType' object has no attribute 'replace'
2023-05-11 00:47:21 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'NoneType' object has no attribute 'replace'
2023-05-11 00:49:31 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'NoneType' object has no attribute 'replace'
2023-05-11 00:51:50 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'datetime.datetime' object is not callable
2023-05-11 00:52:39 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'datetime.datetime' object is not callable
2023-05-11 00:52:40 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'datetime.datetime' object is not callable
2023-05-11 00:52:41 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'datetime.datetime' object is not callable
2023-05-11 00:56:42 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'NoneType' object is not subscriptable
2023-05-11 00:57:36 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'NoneType' object is not subscriptable
2023-05-11 00:59:27 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'NoneType' object is not subscriptable
2023-05-11 00:59:28 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'NoneType' object is not subscriptable
2023-05-11 00:59:29 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'NoneType' object is not subscriptable
2023-05-11 00:59:29 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'NoneType' object is not subscriptable
2023-05-11 01:00:12 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'datetime.datetime' object is not callable
2023-05-11 01:00:40 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'datetime.datetime' object is not callable
2023-05-11 01:00:41 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'datetime.datetime' object is not callable
2023-05-11 01:02:17 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: name 'pod_image' is not defined
2023-05-11 01:02:19 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: name 'pod_image' is not defined
2023-05-11 01:02:19 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: name 'pod_image' is not defined
2023-05-11 01:02:34 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'NoneType' object is not subscriptable
2023-05-11 01:03:02 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'NoneType' object is not subscriptable
2023-05-11 01:03:41 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'NoneType' object is not subscriptable
2023-05-11 01:03:41 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'NoneType' object is not subscriptable
2023-05-11 01:03:42 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'NoneType' object is not subscriptable
2023-05-11 01:08:06 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'NoneType' object is not subscriptable
2023-05-11 01:08:07 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'NoneType' object is not subscriptable
2023-05-11 01:08:08 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'NoneType' object is not subscriptable
2023-05-11 01:08:08 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'NoneType' object is not subscriptable
2023-05-11 01:08:09 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'NoneType' object is not subscriptable
2023-05-11 01:08:09 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'NoneType' object is not subscriptable
2023-05-11 01:08:10 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'NoneType' object is not subscriptable
2023-05-11 01:08:11 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'NoneType' object is not subscriptable
2023-05-11 01:18:41 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: can only concatenate str (not "int") to str
2023-05-11 12:09:57 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'V1ContainerPort' object has no attribute 'get'
2023-05-11 12:09:57 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'V1ContainerPort' object has no attribute 'get'
2023-05-11 12:10:05 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'V1ContainerPort' object has no attribute 'get'
2023-05-11 12:10:23 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'V1ContainerPort' object has no attribute 'get'
2023-05-11 12:10:26 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'V1ContainerPort' object has no attribute 'get'
2023-05-11 12:29:43 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace kube-system: append() takes exactly one argument (3 given)
2023-05-11 12:29:52 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: append() takes exactly one argument (3 given)
2023-05-11 12:29:58 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: append() takes exactly one argument (3 given)
2023-05-11 12:30:04 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: append() takes exactly one argument (3 given)
2023-05-11 12:59:01 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,(pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'ops-kube_manage-mysql' ([Errno 61] Connection refused)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-05-11 12:59:11 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,(pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'ops-kube_manage-mysql' ([Errno 61] Connection refused)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-05-11 12:59:45 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,(pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'ops-kube_manage-mysql' ([Errno 61] Connection refused)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-05-11 12:59:45 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,(pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'ops-kube_manage-mysql' ([Errno 61] Connection refused)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-05-11 12:59:45 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,(pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'ops-kube_manage-mysql' ([Errno 61] Connection refused)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-05-11 12:59:45 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,(pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'ops-kube_manage-mysql' ([Errno 61] Connection refused)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-05-11 12:59:45 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,(pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'ops-kube_manage-mysql' ([Errno 61] Connection refused)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-05-11 12:59:45 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,(pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'ops-kube_manage-mysql' ([Errno 61] Connection refused)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-05-14 17:26:31 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to restart Pod ops-nginx-v4-569f8f6ccb-n7wct in namespace dev: name 'namespace' is not defined
2023-05-14 17:31:28 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to restart Pod ops-nginx-v4-569f8f6ccb-n7wct in namespace dev: name 'namespace' is not defined
2023-05-14 17:31:45 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to restart Pod ops-nginx-v4-569f8f6ccb-n7wct in namespace dev: name 'namespace' is not defined
2023-05-14 17:33:37 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to restart Pod ops-nginx-v4-569f8f6ccb-n7wct in namespace dev: name 'namespace' is not defined
2023-05-14 17:38:27 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to restart Pod ops-nginx-v4-569f8f6ccb-n7wct in namespace dev: 'NoneType' object does not support item assignment
2023-05-14 17:39:23 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to restart Pod ops-nginx-v4-569f8f6ccb-n7wct in namespace dev: 'NoneType' object does not support item assignment
2023-05-14 17:40:11 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to restart Pod ops-nginx-v4-569f8f6ccb-n7wct in namespace dev: 'NoneType' object does not support item assignment
2023-05-14 17:40:50 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to restart Pod ops-nginx-v4-569f8f6ccb-n7wct in namespace dev: 'NoneType' object does not support item assignment
2023-05-14 17:41:26 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to restart Pod ops-nginx-v4-569f8f6ccb-n7wct in namespace dev: 'NoneType' object does not support item assignment
2023-05-14 17:47:22 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Pod ops-nginx-v4-569f8f6ccb-n7wct in namespace dev restarted successfully!
2023-05-14 17:47:43 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Pod ops-nginx-v4-569f8f6ccb-n7wct in namespace dev restarted successfully!
2023-05-14 17:48:28 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Pod ops-nginx-v4-569f8f6ccb-n7wct in namespace dev restarted successfully!
2023-05-14 17:49:25 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Pod ops-nginx-v4-569f8f6ccb-n7wct in namespace dev restarted successfully!
2023-05-14 17:51:02 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Pod ops-nginx-v4-569f8f6ccb-n7wct in namespace dev restarted successfully!
2023-05-14 17:57:40 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Pod ops-nginx-v5-57d794ddd4-489wc in namespace dev is not running, cannot be restarted.
2023-05-14 17:58:30 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Pod ops-nginx-v4-569f8f6ccb-n7wct in namespace dev restarted successfully!
2023-05-14 18:00:08 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Pod ops-nginx-v4-569f8f6ccb-n7wct in namespace dev restarted successfully!
2023-05-14 18:02:41 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Pod ops-nginx-v4-569f8f6ccb-n7wct in namespace dev restarted successfully!
2023-05-14 18:04:59 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Pod ops-nginx-v4-569f8f6ccb-n7wct in namespace dev restarted successfully!
2023-05-14 18:26:19 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Pod ops-nginx-v4-569f8f6ccb-n7wct in namespace dev deleted successfully!
2023-05-14 18:26:21 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to restart Pod ops-nginx-v4-569f8f6ccb-n7wct in namespace dev: name 'ApiException' is not defined
2023-05-14 18:27:29 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Pod ops-nginx-v4-569f8f6ccb-stv9r in namespace dev deleted successfully!
2023-05-14 18:27:31 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to restart Pod ops-nginx-v4-569f8f6ccb-stv9r in namespace dev: name 'ApiException' is not defined
2023-05-14 18:29:06 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Pod ops-nginx-v4-569f8f6ccb-h4t2f in namespace dev deleted successfully!
2023-05-14 18:29:08 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to restart Pod ops-nginx-v4-569f8f6ccb-h4t2f in namespace dev: name 'ApiException' is not defined
2023-05-14 18:29:32 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Pod ops-nginx-v4-569f8f6ccb-59p5v in namespace dev deleted successfully!
2023-05-14 18:29:32 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Pod ops-nginx-v4-569f8f6ccb-59p5v in namespace dev restarted successfully!
2023-05-14 18:32:13 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Pod ops-nginx-v4-569f8f6ccb-dkqwj in namespace dev deleted successfully!
2023-05-14 18:32:13 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Pod ops-nginx-v4-569f8f6ccb-dkqwj in namespace dev restarted successfully!
2023-05-14 18:39:44 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Pod ops-nginx-v4-569f8f6ccb-w2cs9 in namespace dev deleted successfully!
2023-05-14 18:39:44 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Pod ops-nginx-v4-569f8f6ccb-w2cs9 in namespace dev restarted successfully!
2023-05-14 18:45:14 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Pod ops-nginx-v4-569f8f6ccb-cfr9x in namespace dev deleted successfully!
2023-05-14 18:45:14 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Pod ops-nginx-v4-569f8f6ccb-cfr9x in namespace dev restarted successfully!
2023-05-14 19:01:13 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Pod ops-nginx-v4-569f8f6ccb-kgdcs in namespace dev deleted successfully!
2023-05-14 19:01:13 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Pod ops-nginx-v4-569f8f6ccb-kgdcs in namespace dev restarted successfully!
2023-05-14 19:01:54 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Pod ops-nginx-v4-569f8f6ccb-6jg2n in namespace dev deleted successfully!
2023-05-14 19:01:55 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Pod ops-nginx-v4-569f8f6ccb-6jg2n in namespace dev restarted successfully!
2023-05-14 19:03:21 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Pod ops-nginx-v4-569f8f6ccb-4nmmt in namespace dev deleted successfully!
2023-05-14 19:03:21 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Pod ops-nginx-v4-569f8f6ccb-4nmmt in namespace dev restarted successfully!
2023-05-14 19:04:04 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Pod ops-nginx-v4-569f8f6ccb-g89mw in namespace dev deleted successfully!
2023-05-14 19:04:04 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Pod ops-nginx-v4-569f8f6ccb-g89mw in namespace dev restarted successfully!
2023-05-14 20:31:32 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Pod ops-nginx-v4-569f8f6ccb-v79bh in namespace dev deleted successfully!
2023-05-14 20:31:32 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Pod ops-nginx-v4-569f8f6ccb-v79bh in namespace dev restarted successfully!
2023-05-14 20:35:46 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Pod nginx-ops-v1 in namespace dev  Pod created successfully
2023-05-14 20:50:26 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Pod nginx-ops-v1 in namespace dev deleted successfully!
2023-05-14 20:50:26 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Pod nginx-ops-v1 in namespace dev restarted successfully!
2023-05-14 20:52:10 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Pod nginx-test-pod in namespace dev  Pod created successfully
2023-05-14 21:04:12 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Pod ops-nginx-v4-569f8f6ccb-x8xbq in namespace dev deleted successfully!
2023-05-14 21:04:12 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Pod ops-nginx-v4-569f8f6ccb-x8xbq in namespace dev restarted successfully!
2023-05-14 21:49:55 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Container nginx-test-pod in Pod nginx-test-pod of namespace dev updated successfully to image nginx:1.22.1!
2023-05-14 21:50:15 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Container nginx-test-pod in Pod nginx-test-pod of namespace dev updated successfully to image nginx:1.22.12!
2023-05-14 22:16:16 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: name 'qos_class' is not defined
2023-05-14 22:16:17 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: name 'qos_class' is not defined
2023-05-14 22:16:17 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: name 'qos_class' is not defined
2023-05-14 22:16:21 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: name 'qos_class' is not defined
2023-05-14 22:16:22 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: name 'qos_class' is not defined
2023-05-14 22:16:41 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: name 'qos_class' is not defined
2023-05-14 22:17:37 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: name 'qos_class' is not defined
2023-05-14 22:17:38 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: name 'qos_class' is not defined
2023-05-14 22:17:42 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: name 'qos_class' is not defined
2023-05-14 22:17:47 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: name 'qos_class' is not defined
2023-05-14 22:18:06 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: name 'qos_class' is not defined
2023-05-14 22:18:41 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: name 'qos_class' is not defined
2023-05-14 22:18:48 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: name 'qos_class' is not defined
2023-05-14 22:19:04 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: name 'qos_class' is not defined
2023-05-14 22:31:03 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'list' object has no attribute 'state'
2023-05-14 22:31:04 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'list' object has no attribute 'state'
2023-05-14 22:31:16 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'list' object has no attribute 'state'
2023-05-14 22:31:17 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'list' object has no attribute 'state'
2023-05-14 22:41:16 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'NoneType' object has no attribute 'reason'
2023-05-14 22:41:17 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: 'NoneType' object has no attribute 'reason'
2023-05-14 23:06:05 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: local variable 'qos_class' referenced before assignment
2023-05-14 23:06:06 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: local variable 'qos_class' referenced before assignment
2023-05-14 23:07:08 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: local variable 'qos_class' referenced before assignment
2023-05-14 23:07:30 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: local variable 'qos_class' referenced before assignment
2023-05-14 23:07:30 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: local variable 'qos_class' referenced before assignment
2023-05-14 23:08:21 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: local variable 'qos_class' referenced before assignment
2023-05-14 23:15:59 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: local variable 'qos_class' referenced before assignment
2023-05-14 23:15:59 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: local variable 'qos_class' referenced before assignment
2023-05-14 23:16:06 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Failed to delete Pod  in namespace dev: local variable 'qos_class' referenced before assignment
2023-05-14 23:21:35 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Container nginx-test-pod in Pod nginx-test-pod of namespace dev updated successfully to image nginx:1.22.1!
2023-05-14 23:46:35 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Pod nginx-test-s3 in namespace dev  Pod created successfully
2023-05-14 23:47:57 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Container nginx-test-s3 in Pod nginx-test-s3 of namespace dev updated successfully to image nginx:1.22.12!
2023-05-15 00:04:18 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Pod nginx-test-s3 in namespace dev deleted successfully!
2023-05-15 00:04:18 INFO Logging initialized. Log file: /Users/lijianxing/lijx-devops/python/fastapi/op-kube-manage-api/logs/fastapi.log,Pod nginx-test-s3 in namespace dev restarted successfully!
